import type { Theme } from './types'

export const cosaNostra: Theme = {
  id: 'cosaNostra',
  name: 'Cosa Nostra',
  tagline: "It's a nice town. Be a shame if it stayed that way.",
  category: 'crime',
  place: 'the city',
  factionNames: { village: 'Citizens', mafia: 'The Family', neutral: 'Freelancers' },
  roleSkins: {
    villager: { name: 'Citizen', flavour: 'You pay your taxes and you keep your head down. Not tonight.' },
    werewolf: { name: 'Made Man', flavour: "You know the others. Nothing about tonight is personal." },
    seer: { name: 'Private Eye', flavour: 'One file a night. You will know. Proving it is your problem.' },
    doctor: { name: 'Surgeon', flavour: 'You keep people breathing who should not be. One a night.' },
    bodyguard: { name: 'Muscle', flavour: 'You take the bullet. That is the entire job description.' },
    hunter: { name: 'Dead Man Walking', flavour: "If they get you, you are taking somebody with you." },
    witch: { name: 'Chemist', flavour: 'One antidote, one dose. Both work exactly once.' },
    vigilante: { name: 'Cop', flavour: 'Two bullets, no warrant. Shoot a citizen and it ends you.' },
    mayor: { name: 'The Mayor', flavour: 'Say the word and the room votes twice on your say-so.' },
    lycan: { name: 'Ex-Con', flavour: 'Clean now. The file says otherwise. It always will.' },
    minion: { name: 'Associate', flavour: 'You know the Family. They have never heard of you.' },
    alpha: { name: 'The Don', flavour: 'Once, you call a hit no surgeon walks back.' },
    cupid: { name: 'Fixer', flavour: 'You tie two people together. One goes down, both go down.' },
    jester: { name: 'Patsy', flavour: 'Get yourself convicted. That is the win.' },
    serialKiller: { name: 'The Butcher', flavour: 'No family, no orders, no witnesses.' },
    executioner: { name: 'Grudge', flavour: 'One name. Watch the city convict them and you are done.' },
    blackmailer: { name: 'Blackmailer', flavour: 'You own a photograph. They will not say a word tomorrow.' },
    prince: { name: "Senator's Kid", flavour: 'The first conviction does not stick. The second will.' },
    gravedigger: { name: 'Coroner', flavour: 'The bodies tell you exactly who they were.' },
    priest: { name: 'Father Vincent', flavour: 'One blessing. Nothing touches them for a day and a night.' },
    sleepwalker: { name: 'Insomniac', flavour: 'You do not sleep. You know if the night was quiet.' },
  },
  narration: {
    nightFall: 'The city goes quiet. Everybody — eyes down.',
    wolvesWake: "The Family, wake up. Who doesn't see morning?",
    seerWake: 'Detective. One file. Who are we looking at?',
    doctorWake: 'Doc, you are up. Who lives through this?',
    dawn: 'Morning. The papers are already printing.',
    noDeath: 'Nobody died last night. In this city, that is strange.',
    day: 'You have until the deadline. Find the Family.',
    vote: "That's time. Who are we naming?",
    execution: "The vote's in. Nothing personal.",
  },
  deathFlavour: {
    mafia_kill: "didn't come home last night.",
    serial_killer: 'was found in pieces. The Family are denying it, and this time they mean it.',
    vigilante: 'was shot twice in a stairwell. No badge number.',
    witch_poison: 'went face-down in the soup. The lab is still working on it.',
    bodyguard_sacrifice: 'caught it instead. That was the arrangement.',
    lover_grief: "couldn't go on without them. They were found together.",
    hunter_revenge: 'was named on the way down, and named right.',
    execution: 'was walked out in front of everybody.',
    vigilante_guilt: 'turned the gun around before morning.',
  },
  cueOverrides: {
    NIGHT_FALL: 'A slow upright bass. Rain on glass. Very low.',
    WOLVES_WAKE: 'Tap a ring on the table. Twice.',
    EXECUTION: 'One sharp clap. Like a gunshot. Then nothing.',
    DAY: 'Something with brass, under the arguing.',
    VICTORY_MAFIA: 'Something cold and smug. Let it play under the reveal.',
  },
  victory: {
    village: 'The city cleans itself up. For now.',
    mafia: 'The Family owns this town. It always did.',
    neutral: 'Somebody else walked away with it.',
  },
}
