import type { Theme } from './types'

export const cosaNostra: Theme = {
  id: 'cosaNostra',
  name: 'Cosa Nostra',
  tagline: "It's a nice town. Be a shame if it stayed that way.",
  category: 'crime',
  place: 'the city',
  factionNames: { village: 'Citizens', mafia: 'The Family', neutral: 'Freelancers' },
  roleSkins: {
    villager: { name: 'Citizen', flavour: 'You pay your taxes and you keep your head down. Not tonight.' },
    werewolf: { name: 'Made Man', flavour: "You know the others. Nothing about tonight is personal." },
    seer: { name: 'Private Eye', flavour: 'One file a night. You will know. Proving it is your problem.' },
    doctor: { name: 'Surgeon', flavour: 'You keep people breathing who should not be. One a night.' },
    bodyguard: { name: 'Muscle', flavour: 'You take the bullet. That is the entire job description.' },
    hunter: { name: 'Dead Man Walking', flavour: "If they get you, you are taking somebody with you." },
    witch: { name: 'Chemist', flavour: 'One antidote, one dose. Both work exactly once.' },
    vigilante: { name: 'Cop', flavour: 'Two bullets, no warrant. Shoot a citizen and it ends you.' },
    mayor: { name: 'The Mayor', flavour: 'Say the word and the room votes twice on your say-so.' },
    lycan: { name: 'Ex-Con', flavour: 'Clean now. The file says otherwise. It always will.' },
    minion: { name: 'Associate', flavour: 'You know the Family. They have never heard of you.' },
    alpha: { name: 'The Don', flavour: 'Once, you call a hit no surgeon walks back.' },
    cupid: { name: 'Fixer', flavour: 'You tie two people together. One goes down, both go down.' },
    jester: { name: 'Patsy', flavour: 'Get yourself convicted. That is the win.' },
    serialKiller: { name: 'The Butcher', flavour: 'No family, no orders, no witnesses.' },
    executioner: { name: 'Grudge', flavour: 'One name. Watch the city convict them and you are done.' },
    blackmailer: { name: 'Blackmailer', flavour: 'You own a photograph. They will not say a word tomorrow.' },
    prince: { name: "Senator's Kid", flavour: 'The first conviction does not stick. The second will.' },
    gravedigger: { name: 'Coroner', flavour: 'The bodies tell you exactly who they were.' },
    priest: { name: 'Father Vincent', flavour: 'One blessing. Nothing touches them for a day and a night.' },
    sleepwalker: { name: 'Insomniac', flavour: 'You do not sleep. You know if the night was quiet.' },
  },
  narration: {
    nightFall: 'The city goes quiet. Everybody, eyes down.',
    wolvesWake: "The Family, wake up. Who doesn't see morning?",
    seerWake: 'Detective. One file. Who are we looking at?',
    doctorWake: 'Doc, you are up. Who lives through this?',
    dawn: 'Morning. The papers are already printing.',
    noDeath: 'Nobody died last night. In this city, that is strange.',
    day: 'You have until the deadline. Find the Family.',
    vote: "That's time. Who are we naming?",
    execution: "The vote's in. Nothing personal.",
  },
  deathFlavour: {
    mafia_kill: [
      "didn't come home last night.",
      'was last seen getting into a car with people who were very friendly about it.',
      'went out for cigarettes. The Family sends its condolences and a nice wreath.',
      'was found in the boot of their own car, parked very neatly.',
      'took a walk down by the water with two friends and came back with none.',
      'is helping the river with its enquiries.',
    ],
    serial_killer: [
      'was found in pieces. The Family are denying it, and this time they mean it.',
      'was killed in a way nobody in this business would call professional.',
      'got done by somebody freelancing, which everyone agrees is bad for morale.',
      'was done in a way that has upset even the people who do this for a living.',
      'was killed with something borrowed and something sharp. No style at all.',
      "got taken apart by somebody who isn't on anybody's payroll.",
    ],
    vigilante: [
      'was shot twice in a stairwell. No badge number.',
      'caught two from a civilian who has seen too many movies.',
      'was shot by somebody with a licence and a grudge, in that order.',
    ],
    witch_poison: [
      'went face-down in the soup. The lab is still working on it.',
      'had one drink too many, and only one of them was the problem.',
      'died at the table. The restaurant would like it noted that it was not the food.',
    ],
    bodyguard_sacrifice: [
      'caught it instead. That was the arrangement.',
      'stepped in. That was the job, and he was good at it exactly once.',
      'took it for somebody else and never once brought up the overtime.',
    ],
    lover_grief: [
      "couldn't go on without them. They were found together.",
      'was found beside them. Nobody in this city calls that a coincidence.',
      'followed them out. Sentimental, for this line of work.',
    ],
    hunter_revenge: [
      'was named on the way down, and named right.',
      'got named by somebody bleeding out, and the name stuck.',
      'was taken along by a man who did not intend to travel alone.',
    ],
    execution: [
      'was walked out in front of everybody.',
      'got a unanimous vote and a very short walk.',
      'was handled by committee, which is the most democratic thing this town has done.',
      'was voted out by a show of hands, which around here counts as due process.',
      'got walked out by people who had been at their wedding.',
      'was handled in front of the whole room, and the room applauded.',
    ],
    vigilante_guilt: [
      'turned the gun around before morning.',
      'could not square the books with himself.',
      'settled his own account before anybody else got to it.',
    ],
  },
  cueOverrides: {
    NIGHT_FALL: 'A slow upright bass. Rain on glass. Very low.',
    WOLVES_WAKE: 'Tap a ring on the table. Twice.',
    EXECUTION: 'One sharp clap. Like a gunshot. Then nothing.',
    DAY: 'Something with brass, under the arguing.',
    VICTORY_MAFIA: 'Something cold and smug. Let it play under the reveal.',
  },
  victory: {
    village: 'The city cleans itself up. For now.',
    mafia: 'The Family owns this town. It always did.',
    neutral: 'Somebody else walked away with it.',
  },
}
