import type { Theme } from './types'

export const hunterDemon: Theme = {
  id: 'hunterDemon',
  name: 'Hunter × Demon',
  tagline: 'The corps holds the line until dawn. Someone here already broke.',
  category: 'anime',
  place: 'the compound',
  factionNames: { village: 'The Corps', mafia: 'Demons', neutral: 'Strays' },
  roleSkins: {
    villager: { name: 'Recruit', flavour: 'No technique, no rank. Only your eyes and your nerve.' },
    werewolf: { name: 'Demon', flavour: 'You wear a human face until moonrise. The others wear one too.' },
    seer: { name: 'Oracle', flavour: 'You read the aura. One person a night, and you are never wrong.' },
    doctor: { name: 'Medic', flavour: 'Your breathing technique holds one person to this world tonight.' },
    bodyguard: { name: 'Shield Corps', flavour: 'You take the strike meant for them. You do not survive it twice.' },
    hunter: { name: 'Final Form', flavour: 'Your last breath is a technique. Aim it.' },
    witch: { name: 'Poison Master', flavour: 'One antidote. One toxin. Choose the night carefully.' },
    vigilante: { name: 'Rogue Blade', flavour: 'Two strikes, unsanctioned. Cut a comrade and it kills you.' },
    mayor: { name: 'Pillar', flavour: 'Reveal your rank and the corps follows your word twice over.' },
    lycan: { name: 'Tainted Blood', flavour: 'You are human. Your aura screams otherwise.' },
    minion: { name: 'Thrall', flavour: 'You serve them. They do not know your name.' },
    alpha: { name: 'Upper Rank', flavour: 'Once, you strike through any technique that stands in the way.' },
    cupid: { name: 'Bond-Weaver', flavour: 'Two fates, tied. One falls, both fall.' },
    jester: { name: 'Disgraced', flavour: 'Make the corps execute you. That is the victory.' },
    serialKiller: { name: 'The Unclassified', flavour: 'Not demon. Not corps. Every night, one less witness.' },
    executioner: { name: 'Sworn Grudge', flavour: 'One name. See the corps condemn them.' },
    blackmailer: { name: 'Silencer', flavour: 'You hold their shame. They will not speak tomorrow.' },
    prince: { name: 'Heir', flavour: 'The first sentence is commuted. The second is not.' },
    gravedigger: { name: 'Rememberer', flavour: 'You read what the fallen were, exactly.' },
    priest: { name: 'Warding Monk', flavour: 'One ward. Nothing reaches them for a full cycle.' },
    sleepwalker: { name: 'Night Watch', flavour: 'You never sleep. You know if the night claimed anyone.' },
  },
  narration: {
    nightFall: 'The lanterns go out. Everyone — eyes closed.',
    wolvesWake: 'Demons. Open your eyes. Choose tonight.',
    seerWake: 'Oracle. Whose aura do you read?',
    doctorWake: 'Medic. Who breathes until morning?',
    dawn: 'Sunrise. The compound counts heads.',
    noDeath: 'Everyone is standing. Nobody believes that either.',
    day: 'Until dusk. Find the demon wearing a friend.',
    vote: 'Time. Name the accused.',
    execution: 'The corps has judged. Kneel.',
  },
  deathFlavour: {
    mafia_kill: 'was found past the outer gate. Nothing human did that.',
    serial_killer: 'was killed cleanly. No demon kills cleanly.',
    vigilante: 'was cut down in the dark by one of our own blades.',
    witch_poison: 'stopped breathing with no wound at all.',
    bodyguard_sacrifice: 'took the strike meant for someone else.',
    lover_grief: 'followed them. It was never going to go otherwise.',
    hunter_revenge: 'was taken by a dying technique.',
    execution: 'was sentenced in front of the whole corps.',
    vigilante_guilt: 'fell on their own blade before dawn.',
  },
  cueOverrides: {
    NIGHT_FALL: 'Something with a low koto or a single held string.',
    WOLVES_WAKE: 'A wet click. Make it sound wrong.',
    EXECUTION: 'One sharp inhale, then a clap. Sell the silence after.',
    VICTORY_VILLAGE: 'Something soaring. Loud. Let them have it.',
  },
  victory: {
    village: 'Dawn holds. The corps stands. This time.',
    mafia: 'The compound is quiet. Everything inside it is a demon now.',
    neutral: 'Something walked out of here that answered to nobody.',
  },
}
