import type { Theme } from './types'

export const longCourt: Theme = {
  id: 'longCourt',
  name: 'The Long Court',
  tagline: 'Everyone here has already sworn to something. Some of it was winter.',
  category: 'fantasy',
  place: 'the court',
  factionNames: { village: 'The Court', mafia: 'The Winter Pact', neutral: 'Oathless' },
  roleSkins: {
    villager: { name: 'Courtier', flavour: 'No title worth killing for. Only a vote and good ears.' },
    werewolf: { name: 'Winter-sworn', flavour: 'The frost knows your name. It knows the others too.' },
    seer: { name: 'Seer of Ash', flavour: 'The ashes name one soul a night, and never lie.' },
    doctor: { name: 'Hedge-witch', flavour: 'One charm, one throat, one night. Never the same twice running.' },
    bodyguard: { name: 'Sworn Sword', flavour: 'The blade meant for them finds you. That is the oath.' },
    hunter: { name: 'Last Oath', flavour: 'Your dying word takes someone with you. Choose it well.' },
    witch: { name: 'Brewer', flavour: 'One draught calls them back. One sends them on.' },
    vigilante: { name: 'Oathbreaker', flavour: 'Two strikes, unsanctioned. Kill true-court and the oath kills you.' },
    mayor: { name: 'Steward', flavour: 'Take up the rod and the court weighs your voice twice.' },
    lycan: { name: 'Frost-touched', flavour: 'You never swore. The ashes say otherwise. They always will.' },
    minion: { name: 'Frost-thrall', flavour: 'You know the Pact. The Pact has never asked your name.' },
    alpha: { name: 'The Winter King', flavour: 'Once, the frost takes someone no charm can hold.' },
    cupid: { name: 'Oath-Binder', flavour: 'Two bound at the wrist. One falls, both fall.' },
    jester: { name: "The Court's Fool", flavour: 'Make them execute you. That is the entire performance.' },
    serialKiller: { name: 'The Thing Under the Hill', flavour: 'Oathless, nameless, and hungry every night.' },
    executioner: { name: 'The Grudge', flavour: 'One name. See the court condemn them.' },
    blackmailer: { name: 'Keeper of Secrets', flavour: 'You hold their oath-breaking. They will not speak tomorrow.' },
    prince: { name: 'The Heir', flavour: 'The first sentence is refused. The second is carried out.' },
    gravedigger: { name: 'Barrow-keeper', flavour: 'The dead give up their oaths to you, exactly.' },
    priest: { name: 'Oath-Warden', flavour: 'One warding. Nothing touches them for a day and a night.' },
    sleepwalker: { name: 'The Wakeful', flavour: 'You do not sleep. You know if the night took a life.' },
  },
  narration: {
    nightFall: 'The braziers gutter out. Everyone, close your eyes.',
    wolvesWake: 'Winter-sworn, wake. Whose breath stops tonight?',
    seerWake: 'Seer of Ash. Whose name do the ashes give you?',
    doctorWake: 'Hedge-witch. Who do you hold to this side of morning?',
    dawn: 'Frost on the flagstones. The court wakes.',
    noDeath: 'Nobody was taken. The Pact does not usually waste a night.',
    day: 'The court is in session. Find the Winter-sworn.',
    vote: 'Enough talk. Name them.',
    execution: 'The court has judged. It is carried out.',
  },
  deathFlavour: {
    mafia_kill: [
      'was found rimed with frost, in a corridor that has no windows.',
      'was found frozen in a room that has been warm for a hundred years.',
      'was found cold in the east wing, and the frost had come from the inside.',
      'was found in the solar, frozen, with the fire still burning beside them.',
      'was found in a stairwell with frost on the inside of their collar.',
      'was found cold before a hearth that was still hot.',
    ],
    serial_killer: [
      'was killed with something old and not at all cold.',
      'was killed by something with a grudge and no interest in winter.',
      'died by a hand that owes the winter nothing at all.',
      'was killed with a knife, which the winter has never once needed.',
      'was killed by something warm-blooded and entirely uninterested in oaths.',
      'died by ordinary steel, which at this court is almost refreshing.',
    ],
    vigilante: [
      'was struck down by a blade nobody at this table will claim.',
      'was run through by a courtier who was quite certain at the time.',
      'took a blade from someone at this table, who is presently studying the floor.',
    ],
    witch_poison: [
      'drank at supper and never rose from the table.',
      'was poured for generously, and did not survive the hospitality.',
      'took wine at the high table, and stayed there.',
    ],
    bodyguard_sacrifice: [
      'took the blade meant for another. The oath held.',
      'stepped into the stroke. Oaths are, occasionally, honoured.',
      "took it in another's place, exactly as sworn, to everyone's surprise.",
    ],
    lover_grief: [
      'was found beside them, unmarked. The binding held to the end.',
      'did not outlast them by an hour. The binding is not decorative.',
      'followed them out. The court finds this romantic, and inconvenient.',
    ],
    hunter_revenge: [
      'was named by a dying voice, and the naming took.',
      'was named aloud by somebody already falling, and the naming carried.',
      'was taken by a last word, spoken properly.',
    ],
    execution: [
      'was condemned before the full court.',
      'was condemned by acclaim, which this court finds tidier than evidence.',
      'was sentenced before the full court, and the vote was not close.',
      'was condemned in open court, and the vote was taken twice for the look of it.',
      'was condemned before the throne, on testimony nobody has offered to repeat.',
      'was sentenced by a court that was very sure, and is now very quiet.',
    ],
    vigilante_guilt: [
      'was taken by their own broken oath before morning.',
      'broke an oath, and the oath collected before dawn.',
      'could not stand under what they had sworn, and then undone.',
    ],
  },
  cueOverrides: {
    NIGHT_FALL: 'Something with a high, thin, cold tone. Very quiet.',
    WOLVES_WAKE: 'Breathe out slowly, close to the table. Make it audible.',
    EXECUTION: 'One single struck bell, if you have anything that rings.',
    VICTORY_MAFIA: 'Something beautiful and completely cold.',
  },
  victory: {
    village: 'The frost draws back. The court holds, this winter at least.',
    mafia: 'The Long Court belongs to winter now. It is very quiet, and very beautiful.',
    neutral: 'An oath nobody swore has been kept.',
  },
}
