import type { Theme } from './types'

export const longCourt: Theme = {
  id: 'longCourt',
  name: 'The Long Court',
  tagline: 'Everyone here has already sworn to something. Some of it was winter.',
  category: 'fantasy',
  place: 'the court',
  factionNames: { village: 'The Court', mafia: 'The Winter Pact', neutral: 'Oathless' },
  roleSkins: {
    villager: { name: 'Courtier', flavour: 'No title worth killing for. Only a vote and good ears.' },
    werewolf: { name: 'Winter-sworn', flavour: 'The frost knows your name. It knows the others too.' },
    seer: { name: 'Seer of Ash', flavour: 'The ashes name one soul a night, and never lie.' },
    doctor: { name: 'Hedge-witch', flavour: 'One charm, one throat, one night. Never the same twice running.' },
    bodyguard: { name: 'Sworn Sword', flavour: 'The blade meant for them finds you. That is the oath.' },
    hunter: { name: 'Last Oath', flavour: 'Your dying word takes someone with you. Choose it well.' },
    witch: { name: 'Brewer', flavour: 'One draught calls them back. One sends them on.' },
    vigilante: { name: 'Oathbreaker', flavour: 'Two strikes, unsanctioned. Kill true-court and the oath kills you.' },
    mayor: { name: 'Steward', flavour: 'Take up the rod and the court weighs your voice twice.' },
    lycan: { name: 'Frost-touched', flavour: 'You never swore. The ashes say otherwise. They always will.' },
    minion: { name: 'Frost-thrall', flavour: 'You know the Pact. The Pact has never asked your name.' },
    alpha: { name: 'The Winter King', flavour: 'Once, the frost takes someone no charm can hold.' },
    cupid: { name: 'Oath-Binder', flavour: 'Two bound at the wrist. One falls, both fall.' },
    jester: { name: "The Court's Fool", flavour: 'Make them execute you. That is the entire performance.' },
    serialKiller: { name: 'The Thing Under the Hill', flavour: 'Oathless, nameless, and hungry every night.' },
    executioner: { name: 'The Grudge', flavour: 'One name. See the court condemn them.' },
    blackmailer: { name: 'Keeper of Secrets', flavour: 'You hold their oath-breaking. They will not speak tomorrow.' },
    prince: { name: 'The Heir', flavour: 'The first sentence is refused. The second is carried out.' },
    gravedigger: { name: 'Barrow-keeper', flavour: 'The dead give up their oaths to you, exactly.' },
    priest: { name: 'Oath-Warden', flavour: 'One warding. Nothing touches them for a day and a night.' },
    sleepwalker: { name: 'The Wakeful', flavour: 'You do not sleep. You know if the night took a life.' },
  },
  narration: {
    nightFall: 'The braziers gutter out. Everyone — close your eyes.',
    wolvesWake: 'Winter-sworn, wake. Whose breath stops tonight?',
    seerWake: 'Seer of Ash. Whose name do the ashes give you?',
    doctorWake: 'Hedge-witch. Who do you hold to this side of morning?',
    dawn: 'Frost on the flagstones. The court wakes.',
    noDeath: 'Nobody was taken. The Pact does not usually waste a night.',
    day: 'The court is in session. Find the Winter-sworn.',
    vote: 'Enough talk. Name them.',
    execution: 'The court has judged. It is carried out.',
  },
  deathFlavour: {
    mafia_kill: 'was found rimed with frost, in a corridor that has no windows.',
    serial_killer: 'was killed with something old and not at all cold.',
    vigilante: 'was struck down by a blade nobody at this table will claim.',
    witch_poison: 'drank at supper and never rose from the table.',
    bodyguard_sacrifice: 'took the blade meant for another. The oath held.',
    lover_grief: 'was found beside them, unmarked. The binding held to the end.',
    hunter_revenge: 'was named by a dying voice, and the naming took.',
    execution: 'was condemned before the full court.',
    vigilante_guilt: 'was taken by their own broken oath before morning.',
  },
  cueOverrides: {
    NIGHT_FALL: 'Something with a high, thin, cold tone. Very quiet.',
    WOLVES_WAKE: 'Breathe out slowly, close to the table. Make it audible.',
    EXECUTION: 'One single struck bell, if you have anything that rings.',
    VICTORY_MAFIA: 'Something beautiful and completely cold.',
  },
  victory: {
    village: 'The frost draws back. The court holds — this winter, at least.',
    mafia: 'The Long Court belongs to winter now. It is very quiet, and very beautiful.',
    neutral: 'An oath nobody swore has been kept.',
  },
}
