import type { Theme } from './types'

export const millersHollow: Theme = {
  id: 'millersHollow',
  name: 'Remus Vale',
  tagline: 'Something is wrong in the woods.',
  category: 'horror',
  place: 'the village',
  factionNames: { village: 'Villagers', mafia: 'Werewolves', neutral: 'The Unaligned' },
  roleSkins: {
    villager: { name: 'Villager', flavour: 'You have no gift but your own judgement. Use it.' },
    werewolf: { name: 'Werewolf', flavour: 'The change takes you at moonrise. You are not alone.' },
    seer: { name: 'Seer', flavour: 'You see what walks beneath the skin. Say nothing too soon.' },
    doctor: { name: 'Healer', flavour: 'You know which herbs hold death at the door. One night, one life.' },
    bodyguard: { name: 'Warden', flavour: 'You stand between the wolf and the door. You do not step aside.' },
    hunter: { name: 'Hunter', flavour: 'If you fall, your last shot is already aimed.' },
    witch: { name: 'Witch', flavour: 'Two vials. One gives back a life. One takes it.' },
    vigilante: { name: 'Poacher', flavour: 'Two shots, and no one to forgive you if you are wrong.' },
    mayor: { name: 'Elder', flavour: 'The village listens to you, once you decide to be heard.' },
    lycan: { name: 'Cursed', flavour: 'You are no wolf. The Seer will not believe you.' },
    minion: { name: 'Servant', flavour: 'You know their faces. They will never know yours.' },
    alpha: { name: 'Alpha', flavour: 'Once, the pack hunts as one, and no herb will help them.' },
    cupid: { name: 'Matchmaker', flavour: 'You bind two hearts. Neither survives the other.' },
    jester: { name: 'Fool', flavour: 'Make them hang you. That is the whole trick.' },
    serialKiller: { name: 'The Thing in the Woods', flavour: 'You are not a wolf. You are worse.' },
    executioner: { name: 'Grudge', flavour: 'One name. See them swing and you have won.' },
    blackmailer: { name: 'Whisperer', flavour: 'You know a secret. They will keep quiet all day.' },
    prince: { name: "Lord's Son", flavour: 'The first rope will not hold you. The second will.' },
    gravedigger: { name: 'Gravedigger', flavour: 'The dead still answer, if you ask them properly.' },
    priest: { name: 'Priest', flavour: 'One blessing. Nothing touches them for a day and a night.' },
    sleepwalker: { name: 'Sleepwalker', flavour: 'You wander. You know whether the night took someone.' },
  },
  narration: {
    nightFall: 'Night falls on the village. Everyone, close your eyes.',
    wolvesWake: 'Werewolves, open your eyes. Choose your prey.',
    seerWake: 'Seer, awaken. Whose soul will you read?',
    doctorWake: 'Healer, wake. Who lives through tonight?',
    dawn: 'The sun rises over the village.',
    noDeath: 'Somehow, everyone is still breathing. That should worry you.',
    day: 'You have until the light goes. Find the wolves among you.',
    vote: 'Time is up. Who stands accused?',
    execution: 'The village has spoken. To the square.',
  },
  deathFlavour: {
    mafia_kill: [
      'was found at the treeline, and not all of them was found.',
      'was found past the fence line. The dogs would not go out that far.',
      'did not make it back from the barn. The door was open from the inside.',
      'was found at the bottom of the field, with the frost churned up all around them.',
      'was taken between the house and the gate. That is nine steps, in the open.',
      'did not get the door shut in time. It was not locked from the inside this time.',
    ],
    serial_killer: [
      'was left in the road. This was not a wolf.',
      'was killed neatly, which is the frightening part. Wolves are not neat.',
      'was found behind a door that was locked, with the key still turned.',
      'was killed with a knife from their own kitchen, which was put back afterwards.',
      'died indoors, tidily, with nothing broken and nothing taken.',
      'was killed by somebody who took their time about it.',
    ],
    vigilante: [
      'was shot through the dark. The shooter is not saying.',
      'took a shot from somebody who was very sure at the time.',
      'was shot once, cleanly, by a neighbour with a gun and a conscience.',
    ],
    witch_poison: [
      'went cold in their bed, with no mark on them at all.',
      'drank something kind and did not wake for it.',
      'died tidily, in their sleep, which fooled nobody.',
    ],
    bodyguard_sacrifice: [
      'stepped in front of it, and did not step back.',
      'got there first. That was the whole idea, and it worked exactly once.',
      'took it instead, and had not mentioned they were going to.',
    ],
    lover_grief: [
      'could not be woken once they were gone. Grief took what the night left.',
      'followed them before the sun was properly up.',
      'was found beside them, having settled the matter privately.',
    ],
    hunter_revenge: [
      'was taken by a dying hand.',
      'was pointed at by somebody on their way out, and that was enough.',
      'went down second, which is no comfort at all.',
    ],
    execution: [
      'was hanged at the square, in front of everyone.',
      'was walked to the square by people who had known them for years.',
      'was hanged, and the village went home and had its tea.',
      'was put on the cart while half the village looked at their boots.',
      'was hanged before noon. Nobody can agree afterwards who voted for it.',
      'was hanged, and three people have already changed their story about it.',
    ],
    vigilante_guilt: [
      'could not live with what the shot had done.',
      'put the gun down, and did not come back inside.',
      'was found in the barn, having settled it with themselves.',
    ],
  },
  cueOverrides: {
    NIGHT_FALL: 'Wind and distant howling. Kill the lights.',
    WOLVES_WAKE: 'Scrape your nails on the table. Slowly.',
    EXECUTION: 'One heavy stomp. Then nothing.',
    DAWN: 'Silence. Two full seconds. Then speak.',
    VICTORY_MAFIA: 'Let the howling run under the reveal. Do not talk over it.',
  },
  victory: {
    village: 'The woods are quiet. The village survives.',
    mafia: 'The howling stops. There is no one left to hear it.',
    neutral: 'Nobody won this. Something else did.',
  },
}
