import type { Theme } from './types'

export const millersHollow: Theme = {
  id: 'millersHollow',
  name: 'Millers Hollow',
  tagline: 'Something is wrong in the woods.',
  category: 'horror',
  place: 'the village',
  factionNames: { village: 'Villagers', mafia: 'Werewolves', neutral: 'The Unaligned' },
  roleSkins: {
    villager: { name: 'Villager', flavour: 'You have no gift but your own judgement. Use it.' },
    werewolf: { name: 'Werewolf', flavour: 'The change takes you at moonrise. You are not alone.' },
    seer: { name: 'Seer', flavour: 'You see what walks beneath the skin. Say nothing too soon.' },
    doctor: { name: 'Healer', flavour: 'You know which herbs hold death at the door. One night, one life.' },
    bodyguard: { name: 'Warden', flavour: 'You stand between the wolf and the door. You do not step aside.' },
    hunter: { name: 'Hunter', flavour: 'If you fall, your last shot is already aimed.' },
    witch: { name: 'Witch', flavour: 'Two vials. One gives back a life. One takes it.' },
    vigilante: { name: 'Poacher', flavour: 'Two shots, and no one to forgive you if you are wrong.' },
    mayor: { name: 'Elder', flavour: 'The village listens to you, once you decide to be heard.' },
    lycan: { name: 'Cursed', flavour: 'You are no wolf. The Seer will not believe you.' },
    minion: { name: 'Servant', flavour: 'You know their faces. They will never know yours.' },
    alpha: { name: 'Alpha', flavour: 'Once, the pack hunts as one, and no herb will help them.' },
    cupid: { name: 'Matchmaker', flavour: 'You bind two hearts. Neither survives the other.' },
    jester: { name: 'Fool', flavour: 'Make them hang you. That is the whole trick.' },
    serialKiller: { name: 'The Thing in the Woods', flavour: 'You are not a wolf. You are worse.' },
    executioner: { name: 'Grudge', flavour: 'One name. See them swing and you have won.' },
    blackmailer: { name: 'Whisperer', flavour: 'You know a secret. They will keep quiet all day.' },
    prince: { name: "Lord's Son", flavour: 'The first rope will not hold you. The second will.' },
    gravedigger: { name: 'Gravedigger', flavour: 'The dead still answer, if you ask them properly.' },
    priest: { name: 'Priest', flavour: 'One blessing. Nothing touches them for a day and a night.' },
    sleepwalker: { name: 'Sleepwalker', flavour: 'You wander. You know whether the night took someone.' },
  },
  narration: {
    nightFall: 'Night falls on the village. Everyone, close your eyes.',
    wolvesWake: 'Werewolves, open your eyes. Choose your prey.',
    seerWake: 'Seer, awaken. Whose soul will you read?',
    doctorWake: 'Healer, wake. Who lives through tonight?',
    dawn: 'The sun rises over the village.',
    noDeath: 'Somehow, everyone is still breathing. That should worry you.',
    day: 'You have until the light goes. Find the wolves among you.',
    vote: 'Time is up. Who stands accused?',
    execution: 'The village has spoken. To the square.',
  },
  deathFlavour: {
    mafia_kill: 'was found at the treeline, and not all of them was found.',
    serial_killer: 'was left in the road. This was not a wolf.',
    vigilante: 'was shot through the dark. The shooter is not saying.',
    witch_poison: 'went cold in their bed, with no mark on them at all.',
    bodyguard_sacrifice: 'stepped in front of it, and did not step back.',
    lover_grief: 'could not be woken. Grief took what the night left.',
    hunter_revenge: 'was taken by a dying hand.',
    execution: 'was hanged at the square, in front of everyone.',
    vigilante_guilt: 'could not live with what the shot had done.',
  },
  cueOverrides: {
    NIGHT_FALL: 'Wind and distant howling. Kill the lights.',
    WOLVES_WAKE: 'Scrape your nails on the table. Slowly.',
    EXECUTION: 'One heavy stomp. Then nothing.',
    DAWN: 'Silence. Two full seconds. Then speak.',
    VICTORY_MAFIA: 'Let the howling run under the reveal. Do not talk over it.',
  },
  victory: {
    village: 'The woods are quiet. The village survives.',
    mafia: 'The howling stops. There is no one left to hear it.',
    neutral: 'Nobody won this. Something else did.',
  },
}
