import type { Theme } from './types'

export const nightshift: Theme = {
  id: 'nightshift',
  name: 'Nightshift',
  tagline: 'The ward holds the line until dawn. Someone here already broke.',
  category: 'anime',
  place: 'the compound',
  factionNames: { village: 'The Ward', mafia: 'Demons', neutral: 'Strays' },
  roleSkins: {
    villager: { name: 'Recruit', flavour: 'No training, no rank. Only your eyes and your nerve.' },
    werewolf: { name: 'Demon', flavour: 'You wear a human face until moonrise. The others wear one too.' },
    seer: { name: 'Oracle', flavour: 'You read the aura. One person a night, and you are never wrong.' },
    doctor: { name: 'Medic', flavour: 'Your field craft holds one person to this world tonight.' },
    bodyguard: { name: 'Shieldbearer', flavour: 'You take the strike meant for them. You do not survive it twice.' },
    hunter: { name: 'Final Form', flavour: 'Your last breath is a technique. Aim it.' },
    witch: { name: 'Poison Master', flavour: 'One antidote. One toxin. Choose the night carefully.' },
    vigilante: { name: 'Rogue Blade', flavour: 'Two strikes, unsanctioned. Cut a comrade and it kills you.' },
    mayor: { name: 'Banner', flavour: 'Raise your banner and the ward follows your word twice over.' },
    lycan: { name: 'Tainted Blood', flavour: 'You are human. Your aura screams otherwise.' },
    minion: { name: 'Thrall', flavour: 'You serve them. They do not know your name.' },
    alpha: { name: 'Upper Rank', flavour: 'Once, you strike through any technique that stands in the way.' },
    cupid: { name: 'Bond-Weaver', flavour: 'Two fates, tied. One falls, both fall.' },
    jester: { name: 'Disgraced', flavour: 'Make the ward execute you. That is the victory.' },
    serialKiller: { name: 'The Unclassified', flavour: 'Not demon. Not ward. Every night, one less witness.' },
    executioner: { name: 'Sworn Grudge', flavour: 'One name. See the ward condemn them.' },
    blackmailer: { name: 'Silencer', flavour: 'You hold their shame. They will not speak tomorrow.' },
    prince: { name: 'Heir', flavour: 'The first sentence is commuted. The second is not.' },
    gravedigger: { name: 'Rememberer', flavour: 'You read what the fallen were, exactly.' },
    priest: { name: 'Warding Monk', flavour: 'One ward. Nothing reaches them for a full cycle.' },
    sleepwalker: { name: 'Night Watch', flavour: 'You never sleep. You know if the night claimed anyone.' },
  },
  narration: {
    opening:
      'The compound, an hour before full dark. The outer gate held last night, which is more than it managed the week before. Nineteen of us on the wall until dawn. Something came through the treeline at third bell and it has not gone back.',
    intro:
      'Down the line. Name, how long you have served, and what you saw on your last patrol. Loud enough for the back to hear.',
    nightFall: 'The lanterns go out. Everyone, eyes closed.',
    wolvesWake: 'Demons. Open your eyes. Choose tonight.',
    seerWake: 'Oracle. Whose aura do you read?',
    doctorWake: 'Medic. Who breathes until morning?',
    dawn: 'Sunrise. The compound counts heads.',
    noDeath: 'Everyone is standing. Nobody believes that either.',
    day: 'Until dusk. Find the demon wearing a friend.',
    vote: 'Time. Name the accused.',
    execution: 'The ward has judged. Kneel.',
  },
  deathFlavour: {
    mafia_kill: [
      'was found past the outer gate. Nothing human did that.',
      'was found beyond the gate with the blade still sheathed. They never got to draw.',
      'did not return from the perimeter. The gate was open, and it opened outward.',
      'was found at the treeline with the seal broken and the blade still clean.',
      'did not answer the watch call. The perimeter was intact all night.',
      'was found beyond the wall. The ward has stopped counting how many that makes.',
    ],
    serial_killer: [
      'was killed cleanly. No demon kills cleanly.',
      'was cut down with technique. Demons do not have technique.',
      'died to a single clean stroke, which rules out everything we hunt.',
      'was killed with a ward blade. Demons do not carry ward blades.',
      'died to one strike, placed exactly. That is training, not hunger.',
      'was killed by somebody who knew precisely where the armour ends.',
    ],
    vigilante: [
      'was cut down in the dark by one of our own blades.',
      'was struck down by ward steel, with total conviction and no evidence.',
      'fell to one of our own, who was certain, and is now considerably less so.',
    ],
    witch_poison: [
      'stopped breathing with no wound at all.',
      'fell with no wound, no blood, and not a mark on the armour.',
      'simply stopped. Not a scratch on them.',
    ],
    bodyguard_sacrifice: [
      'took the strike meant for someone else.',
      'moved first, and took the whole of it so somebody else would not.',
      'stepped into the strike, smiled about it, and went down.',
    ],
    lover_grief: [
      'followed them. It was never going to go otherwise.',
      'went down within the minute after them. Some bonds do not negotiate.',
      'followed them out, which the whole ward saw coming and nobody could stop.',
    ],
    hunter_revenge: [
      'was taken by a dying strike.',
      'was caught by a last stand nobody knew they had left in them.',
      'was taken by a last breath and a last swing.',
    ],
    execution: [
      'was sentenced in front of the whole ward.',
      'was sentenced by the ward, in formation, in daylight.',
      'knelt before the whole ward, and the ward did not look away.',
      'was sentenced at first light, with the whole ward standing to attention.',
      'was condemned by the ward, and not one blade was raised in their defence.',
      'knelt in the courtyard, and the ward carried out its own sentence.',
    ],
    vigilante_guilt: [
      'fell on their own blade before dawn.',
      'took their own blade before the sun came up.',
      'could not carry the mistake, and settled it in the old way.',
    ],
  },
  cueOverrides: {
    NIGHT_FALL: 'Something with a low koto or a single held string.',
    WOLVES_WAKE: 'A wet click. Make it sound wrong.',
    EXECUTION: 'One sharp inhale, then a clap. Sell the silence after.',
    VICTORY_VILLAGE: 'Something soaring. Loud. Let them have it.',
  },
  victory: {
    village: 'Dawn holds. The ward stands. This time.',
    mafia: 'The compound is quiet. Everything inside it is a demon now.',
    neutral: 'Something walked out of here that answered to nobody.',
  },
}
