import type { Theme } from './types'

export const olympus: Theme = {
  id: 'olympus',
  name: 'Olympus Betrayed',
  tagline: 'Titan blood runs in someone at this table.',
  category: 'myth',
  place: 'the city',
  factionNames: { village: 'Mortals', mafia: 'Titan-blooded', neutral: 'The Unbound' },
  roleSkins: {
    villager: { name: 'Mortal', flavour: 'No gift from any god. Only a vote and a suspicion.' },
    werewolf: { name: 'Titan-blooded', flavour: 'The old blood wakes at night. You are not the only one.' },
    seer: { name: 'Oracle of Delphi', flavour: 'The god speaks through you. One name a night, and truly.' },
    doctor: { name: 'Asclepius', flavour: 'You hold one mortal back from the river tonight.' },
    bodyguard: { name: 'Shield of Ajax', flavour: 'The blow meant for them lands on you instead.' },
    hunter: { name: 'Artemis-Sworn', flavour: 'Your last arrow is loosed as you fall.' },
    witch: { name: 'Circe', flavour: 'One draught restores. One draught ends. Both are final.' },
    vigilante: { name: 'Avenger', flavour: 'Two spears, no sanction. Strike a mortal and the Furies take you.' },
    mayor: { name: 'Archon', flavour: 'Claim the seat and the assembly weighs your voice twice.' },
    lycan: { name: 'God-Touched', flavour: 'Mortal, and yet the Oracle names you Titan. It is a cruel joke.' },
    minion: { name: 'Cultist', flavour: 'You know the old blood. It does not know you.' },
    alpha: { name: 'Firstborn', flavour: 'Once, you strike and no god may intervene.' },
    cupid: { name: 'Eros', flavour: 'Two threads, tied at the wrist. One is cut, both are cut.' },
    jester: { name: 'Scapegoat', flavour: 'Be condemned by the assembly. That alone is your victory.' },
    serialKiller: { name: 'The Fury', flavour: 'You answer to no pantheon. One name a night.' },
    executioner: { name: 'Nemesis', flavour: 'One name. See the assembly condemn them.' },
    blackmailer: { name: 'Harpy', flavour: 'You hold their shame. They speak no word tomorrow.' },
    prince: { name: 'Prince of the House', flavour: 'The first condemnation is refused. The second is not.' },
    gravedigger: { name: 'Charon', flavour: 'The dead give up their names to you.' },
    priest: { name: 'Hierophant', flavour: 'One rite. Nothing touches them for a day and a night.' },
    sleepwalker: { name: 'Sibyl', flavour: 'You dream badly. You know whether the night took a life.' },
  },
  narration: {
    nightFall: 'Night falls on the city. Everyone — close your eyes.',
    wolvesWake: 'Titan-blooded, wake. Whose thread do you cut?',
    seerWake: 'Oracle. The god is listening. Whose name?',
    doctorWake: 'Asclepius. Who do you hold back from the river?',
    dawn: 'Dawn over the temple steps.',
    noDeath: 'Every mortal drew breath. The gods are not usually so kind.',
    day: 'The assembly is open. Find the old blood.',
    vote: 'The assembly will name someone. Now.',
    execution: 'The assembly has judged. It is done.',
  },
  deathFlavour: {
    mafia_kill: 'was found on the temple steps, cold before the priests reached them.',
    serial_killer: 'was taken by something with no altar and no name.',
    vigilante: 'was struck down by a spear no one will claim.',
    witch_poison: 'drank, and did not rise.',
    bodyguard_sacrifice: 'took the blow meant for another and did not rise from it.',
    lover_grief: 'followed them across the river within the hour.',
    hunter_revenge: 'was taken by an arrow loosed from a falling hand.',
    execution: 'was condemned by the assembly, in full view of the gods.',
    vigilante_guilt: 'was taken by the Furies before morning.',
  },
  cueOverrides: {
    NIGHT_FALL: 'A low drone and distant thunder. Dim everything.',
    WOLVES_WAKE: 'A single struck note, let ring.',
    EXECUTION: 'One heavy strike, like a gavel of stone.',
    VICTORY_VILLAGE: 'Something with strings and height. Loud.',
  },
  victory: {
    village: 'The old blood is spent. The city stands.',
    mafia: 'The Titans have their city back. Nobody left to pray.',
    neutral: 'The gods did not choose this ending. Something else did.',
  },
}
