import type { Theme } from './types'

export const salem: Theme = {
  id: 'salem',
  name: 'Salem, 1692',
  tagline: 'The accusation is the evidence.',
  category: 'history',
  place: 'the town',
  factionNames: { village: 'Townsfolk', mafia: 'The Coven', neutral: 'The Unclaimed' },
  roleSkins: {
    villager: { name: 'Townsfolk', flavour: 'You have your reputation and nothing else. Guard it.' },
    werewolf: { name: 'Witch', flavour: 'You meet in the woods after dark. You know the other faces.' },
    seer: { name: 'Reverend', flavour: 'You can see the mark on a soul. One a night.' },
    doctor: { name: 'Midwife', flavour: 'You have kept people alive through worse than this. One a night.' },
    bodyguard: { name: 'Constable', flavour: 'You sleep at their door. Whatever comes takes you first.' },
    hunter: { name: 'Militiaman', flavour: 'If they take you, your musket is already loaded.' },
    witch: { name: 'Apothecary', flavour: 'One tincture restores. One ends it. Neither can be undone.' },
    vigilante: { name: 'Zealot', flavour: 'Two nights of righteous violence. Be right, or it ends you.' },
    mayor: { name: 'Magistrate', flavour: 'Take the bench and the town weighs your word twice.' },
    lycan: { name: 'The Accused', flavour: 'You are innocent. The Reverend will see the mark anyway.' },
    minion: { name: 'Familiar', flavour: 'You know the coven. The coven has never seen you.' },
    alpha: { name: 'Coven Mother', flavour: 'Once, you take someone no midwife can save.' },
    cupid: { name: 'Handfaster', flavour: 'Two bound at the wrist. One is lost, both are lost.' },
    jester: { name: 'The Hysteric', flavour: 'Get yourself hanged. That is all you need.' },
    serialKiller: { name: 'The Thing in the Meetinghouse', flavour: 'No coven. No god. One a night.' },
    executioner: { name: 'The Grudge', flavour: 'One name. See the town hang them.' },
    blackmailer: { name: 'The Whisper', flavour: 'You know what they did. They will be silent tomorrow.' },
    prince: { name: "Governor's Kin", flavour: 'The first rope is cut. The second holds.' },
    gravedigger: { name: 'Sexton', flavour: 'You bury them. You learn exactly what they were.' },
    priest: { name: 'The Blessing', flavour: 'One rite. Nothing touches them for a day and a night.' },
    sleepwalker: { name: 'The Afflicted', flavour: 'You do not sleep. You know if the night took someone.' },
  },
  narration: {
    nightFall: 'The candles go out. Everyone, close your eyes.',
    wolvesWake: 'The Coven, wake. Whose name do you speak tonight?',
    seerWake: 'Reverend. Whose soul do you look upon?',
    doctorWake: 'Midwife. Who sees the morning?',
    dawn: 'Morning over the town. The bell is already ringing.',
    noDeath: 'Nobody was taken. In this town, that will be evidence of something.',
    day: 'The meeting is open. Name the Coven among you.',
    vote: 'Enough. Who stands accused?',
    execution: 'The town has judged. To the gallows.',
  },
  deathFlavour: {
    mafia_kill: 'was found at first light, and the marks were not made by any animal.',
    serial_killer: 'was killed with a blade. The Coven has no need of blades.',
    vigilante: 'was shot in the dark by a hand that thought itself righteous.',
    witch_poison: 'went cold with no wound and no fever.',
    bodyguard_sacrifice: 'stood at the door and did not move.',
    lover_grief: 'was found beside them, unmarked, unbreathing.',
    hunter_revenge: 'was taken by a musket already loaded.',
    execution: 'was hanged before the whole town.',
    vigilante_guilt: 'could not carry what they had done past morning.',
  },
  cueOverrides: {
    NIGHT_FALL: 'Wind under a door. A single low note if you have one.',
    WOLVES_WAKE: 'Whisper it. Do not say it out loud.',
    EXECUTION: 'One flat clap. Let the silence sit far too long.',
    DEATH_REVEAL: 'Drop your voice to nearly nothing. Say the name once.',
  },
  victory: {
    village: 'The town is cleansed. Whether it was ever guilty is another question.',
    mafia: 'The Coven owns the meetinghouse now. Nobody is left to object.',
    neutral: 'Someone got exactly what they came for, and it was not justice.',
  },
}
