import type { Theme } from './types'

export const salem: Theme = {
  id: 'salem',
  name: 'Salem, 1692',
  tagline: 'The accusation is the evidence.',
  category: 'history',
  place: 'the town',
  factionNames: { village: 'Townsfolk', mafia: 'The Coven', neutral: 'The Unclaimed' },
  roleSkins: {
    villager: { name: 'Townsfolk', flavour: 'You have your reputation and nothing else. Guard it.' },
    werewolf: { name: 'Witch', flavour: 'You meet in the woods after dark. You know the other faces.' },
    seer: { name: 'Reverend', flavour: 'You can see the mark on a soul. One a night.' },
    doctor: { name: 'Midwife', flavour: 'You have kept people alive through worse than this. One a night.' },
    bodyguard: { name: 'Constable', flavour: 'You sleep at their door. Whatever comes takes you first.' },
    hunter: { name: 'Militiaman', flavour: 'If they take you, your musket is already loaded.' },
    witch: { name: 'Apothecary', flavour: 'One tincture restores. One ends it. Neither can be undone.' },
    vigilante: { name: 'Zealot', flavour: 'Two nights of righteous violence. Be right, or it ends you.' },
    mayor: { name: 'Magistrate', flavour: 'Take the bench and the town weighs your word twice.' },
    lycan: { name: 'The Accused', flavour: 'You are innocent. The Reverend will see the mark anyway.' },
    minion: { name: 'Familiar', flavour: 'You know the coven. The coven has never seen you.' },
    alpha: { name: 'Coven Mother', flavour: 'Once, you take someone no midwife can save.' },
    cupid: { name: 'Handfaster', flavour: 'Two bound at the wrist. One is lost, both are lost.' },
    jester: { name: 'The Hysteric', flavour: 'Get yourself hanged. That is all you need.' },
    serialKiller: { name: 'The Thing in the Meetinghouse', flavour: 'No coven. No god. One a night.' },
    executioner: { name: 'The Grudge', flavour: 'One name. See the town hang them.' },
    blackmailer: { name: 'The Whisper', flavour: 'You know what they did. They will be silent tomorrow.' },
    prince: { name: "Governor's Kin", flavour: 'The first rope is cut. The second holds.' },
    gravedigger: { name: 'Sexton', flavour: 'You bury them. You learn exactly what they were.' },
    priest: { name: 'The Blessing', flavour: 'One rite. Nothing touches them for a day and a night.' },
    sleepwalker: { name: 'The Afflicted', flavour: 'You do not sleep. You know if the night took someone.' },
  },
  narration: {
    nightFall: 'The candles go out. Everyone, close your eyes.',
    wolvesWake: 'The Coven, wake. Whose name do you speak tonight?',
    seerWake: 'Reverend. Whose soul do you look upon?',
    doctorWake: 'Midwife. Who sees the morning?',
    dawn: 'Morning over the town. The bell is already ringing.',
    noDeath: 'Nobody was taken. In this town, that will be evidence of something.',
    day: 'The meeting is open. Name the Coven among you.',
    vote: 'Enough. Who stands accused?',
    execution: 'The town has judged. To the gallows.',
  },
  deathFlavour: {
    mafia_kill: [
      'was found at first light, and the marks were not made by any animal.',
      'was found cold at first light, with the door still barred from within.',
      'did not rise this morning. There are marks, and no explanation for them.',
      'was found in the yard at dawn, and the ground around them was unmarked.',
      'was taken indoors, with the shutters still fastened from within.',
      'did not rise. The household heard nothing at all in the night.',
    ],
    serial_killer: [
      'was killed with a blade. The Coven has no need of blades.',
      'was killed by a plain hand and a plain knife, which frightens people more.',
      'died by steel. Whatever else walks here, it has no need of steel.',
      'was killed with a knife, by a hand that needed no help from the devil.',
      'was killed plainly, and the plainness of it has frightened the town most.',
      'died by a mortal hand. The town would rather it had been otherwise.',
    ],
    vigilante: [
      'was shot in the dark by a hand that thought itself righteous.',
      'was shot by a neighbour who was certain, and is less certain this morning.',
      "was killed by somebody who believed they were doing God's work.",
    ],
    witch_poison: [
      'went cold with no wound and no fever.',
      'died in the night with no mark, no fever, and no cause the doctor will name.',
      'was found cold and unmarked, which the town has already decided means something.',
    ],
    bodyguard_sacrifice: [
      'stood at the door and did not move.',
      'stood between the door and another, and was found there.',
      'would not stand aside, and paid the whole price for it.',
    ],
    lover_grief: [
      'was found beside them, unmarked, unbreathing.',
      'was found beside them at dawn, cold and without a wound.',
      'did not outlive them by an hour.',
    ],
    hunter_revenge: [
      'was taken by a musket already loaded.',
      'was named and shot by somebody with nothing left to lose.',
      'was taken by a hand that was already dying, and steady all the same.',
    ],
    execution: [
      'was hanged before the whole town.',
      'was hanged on the hill. The town watched, and the town went home.',
      'was hanged on the word of neighbours, and no evidence but the word.',
      'was hanged at the hill, and no evidence was read out but testimony.',
      'was hanged on the strength of what people were sure they had seen.',
      'was hanged. Some of those who voted are already saying they did not.',
    ],
    vigilante_guilt: [
      'could not carry what they had done past morning.',
      'was found at dawn, having judged themselves more harshly than the court would.',
      'could not live beside the grave they had made.',
    ],
  },
  cueOverrides: {
    NIGHT_FALL: 'Wind under a door. A single low note if you have one.',
    WOLVES_WAKE: 'Whisper it. Do not say it out loud.',
    EXECUTION: 'One flat clap. Let the silence sit far too long.',
    DEATH_REVEAL: 'Drop your voice to nearly nothing. Say the name once.',
  },
  victory: {
    village: 'The town is cleansed. Whether it was ever guilty is another question.',
    mafia: 'The Coven owns the meetinghouse now. Nobody is left to object.',
    neutral: 'Someone got exactly what they came for, and it was not justice.',
  },
}
