import type { Theme } from './types'

export const signalLost: Theme = {
  id: 'signalLost',
  name: 'Signal Lost',
  tagline: 'Crew of nineteen. Nineteen heat signatures. One of them is wrong.',
  category: 'scifi',
  place: 'the station',
  factionNames: { village: 'Crew', mafia: 'The Anomaly', neutral: 'Unlogged' },
  roleSkins: {
    villager: { name: 'Crew', flavour: 'No clearance, no scanner. Just what you saw on your shift.' },
    werewolf: { name: 'Assimilated', flavour: 'It wears your file and your face. So do the others.' },
    seer: { name: 'Bio-scanner', flavour: 'One deep scan per cycle. The readout does not lie.' },
    doctor: { name: 'Med-Officer', flavour: 'One stasis pod, one occupant, one cycle.' },
    bodyguard: { name: 'Security', flavour: 'You are between it and them. That is the whole post.' },
    hunter: { name: 'Deadman Switch', flavour: 'If your vitals flatline, something else flatlines with you.' },
    witch: { name: 'Chem-Lab', flavour: 'One revival serum. One neurotoxin. Both single-use.' },
    vigilante: { name: 'Sidearm', flavour: 'Two rounds, unauthorised. Hit a crewmate and you will not survive it.' },
    mayor: { name: 'Commander', flavour: 'Unseal your rank and your vote carries double.' },
    lycan: { name: 'False Positive', flavour: 'You are clean. The scanner disagrees, permanently.' },
    minion: { name: 'Compromised', flavour: 'You know what it is. It does not know about you.' },
    alpha: { name: 'Prime Vector', flavour: 'Once, it breaches any pod, any seal, anything.' },
    cupid: { name: 'Pair-Bond Protocol', flavour: 'Two life-signs linked. One flatlines, both flatline.' },
    jester: { name: 'Scapegoat', flavour: 'Get yourself airlocked by vote. That is the objective.' },
    serialKiller: { name: 'Something Else', flavour: 'Not the Anomaly. Not crew. One kill per cycle.' },
    executioner: { name: 'Vendetta', flavour: 'One name on your manifest. See them airlocked.' },
    blackmailer: { name: 'Comms Jammer', flavour: 'Their channel is cut. No speech, no vote, next cycle.' },
    prince: { name: 'Flag Officer', flavour: 'The first airlock order is overridden. The second is not.' },
    gravedigger: { name: 'Pathologist', flavour: 'The bodies give up exactly what they were.' },
    priest: { name: 'Containment', flavour: 'One full seal. Nothing reaches them for a cycle.' },
    sleepwalker: { name: 'Night Shift', flavour: 'You are awake. You know if the cycle cost someone.' },
  },
  narration: {
    nightFall: 'Lights to night cycle. Everyone, eyes down.',
    wolvesWake: 'Anomaly. Open your eyes. Select a crew member.',
    seerWake: 'Bio-scanner. One deep scan. Who are we reading?',
    doctorWake: 'Med-Officer. One pod. Who goes in it?',
    dawn: 'Cycle end. Roll call.',
    noDeath: 'Full crew accounted for. That has not happened in a while.',
    day: 'You have one shift. Find what is wearing a uniform.',
    vote: 'Shift over. Log your accusation.',
    execution: 'Airlock cycling. Stand clear.',
  },
  deathFlavour: {
    mafia_kill: [
      'was found in the maintenance crawl. What was left was not standard.',
      'is logged as missing. The heat signature count did not change.',
      'was found in a section that had been sealed from the outside.',
      'was found in a compartment that logs no entry and no exit.',
      'stopped transmitting at 0300. The suit telemetry ran on for nine more minutes.',
      'was recovered from deck four. Recovery took some time.',
    ],
    serial_killer: [
      'was killed with a tool. The Anomaly does not use tools.',
      'was killed with something from the workshop. The item is signed out.',
      'died to a blunt instrument, which is not in the Anomaly behavioural profile.',
      'was killed with something from the galley. The galley is not a threat vector.',
      'died to blunt force. The Anomaly has never once used blunt force.',
      'was killed efficiently, which the incident report files as "atypical".',
    ],
    vigilante: [
      'was found with two rounds in them. Sidearm rounds.',
      'was shot with crew-issue ammunition, by crew-issue hands.',
      'took two rounds. Ballistics will match somebody standing at this table.',
    ],
    witch_poison: [
      'flatlined with no trauma and no toxicology flag anyone will admit to.',
      'flatlined clean. Medical has no explanation and is not enjoying that.',
      'stopped, medically, for no reason the scanner is willing to name.',
    ],
    bodyguard_sacrifice: [
      'was between it and someone else. That was the post.',
      'was standing exactly where the post required. The post worked as designed.',
      'interposed. The log records the decision as deliberate.',
    ],
    lover_grief: [
      'flatlined within the minute. The link held.',
      'flatlined sixty seconds behind them. Medical has stopped calling it coincidence.',
      'followed them out. Whatever the link is, it does not survive alone.',
    ],
    hunter_revenge: [
      'was taken by a switch that was already armed.',
      'was caught by a dead-man switch nobody knew had been set.',
      'was taken out by a system somebody armed on the way down.',
    ],
    execution: [
      'was airlocked by unanimous log entry.',
      'was cycled out. The vote is logged, timestamped, and signed by everyone here.',
      'went out the lock. Procedure was followed exactly, which helps nobody.',
      'was cycled out at 0400. The vote carried unanimously and nobody has slept since.',
      'was put out the lock with full consensus and complete documentation.',
      'was voted out of an airlock by people who will file about it later.',
    ],
    vigilante_guilt: [
      'logged out permanently before the next cycle.',
      'filed a final entry and cycled themselves out.',
      'could not carry the ballistics report, and made their own arrangements.',
    ],
  },
  cueOverrides: {
    NIGHT_FALL: 'A reactor hum. Barely there. Just enough to notice when it stops.',
    WOLVES_WAKE: 'A wet click. Like something breathing wrong.',
    EXECUTION: 'An airlock cycling. Hiss, thump, silence.',
    DAWN: 'Cut the hum dead. Let the silence land before you speak.',
  },
  victory: {
    village: 'Station secure. Nineteen files, nineteen matches. Finally.',
    mafia: 'The station reports all clear. There is no one left to report it.',
    neutral: 'Something logged out that was never logged in.',
  },
}
